//
//  LocalizationKeys.swift
//  FlyportApp
//
//  Created by Dovydas Kiriliauskas on 2021-03-12.
//  Copyright © 2021 Dovydas Kiriliauskas. All rights reserved.
//

public enum LocalizationKeys {
	public static let flyPortTitle = "FLYPORT_TITLE"
	public static let flyPortSubtitle = "FLYPORT_SUBTITLE"
	public static let login = "LOGIN"
	public static let register = "REGISTER"
	public static let email = "EMAIL"
	public static let password = "PASSWORD"
	public static let registerTitle = "REGISTER_TITLE"
	public static let unsuccessfulLoginTitle = "UNSUCCESSFUL_LOGIN_TITLE"
	public static let unsuccessfulLoginMessage = "UNSUCCESSFUL_LOGIN_MESSAGE"
	public static let tryAgain = "TRY_AGAIN"
	public static let username = "USERNAME"
	public static let repeatPassword = "REPEAT_PASSWORD"
	public static let loginTitle = "LOGIN_TITLE"
	public static let name = "NAME"
	public static let surname = "SURNAME"
	public static let personalCode = "PERSONAL_CODE"
	public static let documentNumber = "DOCUMENT_NUMBER"
	public static let successfulRegistrationTitle = "SUCCESSFUL_REGISTRATION_TITLE"
	public static let successfulRegistrationSubtitle = "SUCCESSFUL_REGISTRATION_SUBTITLE"
	public static let loginSmall = "LOGIN_SMALL"
	public static let unsuccessfulRegistrationTitle = "UNSUCCESSFUL_REGISTRATION_TITLE"
	public static let unsuccessfulRegistrationSubtitle = "UNSUCCESSFUL_REGISTRATION_SUBTITLE"
	public static let profile = "PROFILE"
	public static let myFlights = "MY_FLIGHTS"
	public static let settings = "SETTINGS"
	public static let newFlight = "NEW_FLIGHT"
	public static let registrationTable = "REGISTRATION_TABLE"
	public static let aviationSecurityPost = "AVIATION_SECURITY_POST"
	public static let passportControlPost = "PASSPORT_CONTROL_POST"
	public static let boardingGates = "BOARDING_GATES"
	public static let successfulUpdateTitle = "SUCCESSFUL_UPDATE_TITLE"
	public static let successfulUpdateSubtitle = "SUCCESSFUL_UPDATE_SUBTITLE"
	public static let ok = "OK"
	public static let unsuccessfulUpdateTitle = "UNSUCCESSFUL_UPDATE_TITLE"
	public static let unsuccessfulUpdateSubtitle = "UNSUCCESSFUL_UPDATE_SUBTITLE"
	public static let yourRegistrationTable = "YOUR_REGISTRATION_TABLE"
	public static let yourAviationSecurityPost = "YOUR_SECURITY_POST"
	public static let yourPassportControlPost = "YOUR_PASSPORT_POST"
	public static let yourBoardingGates = "YOUR_BOARDING_GATES"
	public static let enterFlightNumber = "ENTER_FLIGHT_NUMBER"
	public static let flightNumber = "FLIGHT_NUMBER"
	public static let enterFlightDate = "ENTER_FLIGHT_DATE"
	public static let flightDate = "FLIGHT_DATE"
	public static let select = "SELECT"
	public static let error = "ERROR"
	public static let flightInfoErrorSubtitle = "FLIGHT_INFO_ERROR_SUBTITLE"
	public static let luggageQuestion = "LUGGAGE_QUESTION"
	public static let navigateToRegistration = "NAVIGATE_TO_REGISTRATION"
	public static let showQR = "SHOW_QR"
	public static let moveToNextProcedure = "MOVE_TO_NEXT_PROCEDURE"
	public static let navigateToSecurity = "NAVIGATE_TO_SECURITY"
	public static let navigateToPassport = "NAVIGATE_TO_PASSPORT"
	public static let navigateToBoarding = "NAVIGATE_TO_BOARDING"
	public static let finish = "FINISH"
	public static let congrats = "CONGRATS"
	public static let readyForFlight = "READY_FOR_FLIGHT"
	public static let yourQR = "YOUR_QR"
	public static let hideQR = "HIDE_QR"
	public static let yourSelectedFlight = "YOUR_SELECTED_FLIGHT"
	public static let completedFlight = "COMPLETED_FLIGHT"
	public static let incompletedFlight = "INCOMPLETED_FLIGHT"
	public static let readyForTheTrip = "READY_FOR_THE_TRIP"
	public static let addTrip = "ADD_TRIP"
	public static let haventFliedBefore = "HAVENT_FLIED_BEFORE"
	public static let ops = "OPS"
}
